version: 1
update_configs:
  # Security updates for all node packages
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
    commit_message:
      prefix: "chore"
      include_scope: true
