name: Pre-release

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'

jobs:
  test:
    name: '🧪 Test'
    secrets: inherit
    uses: ./.github/workflows/tests.yml

  gh_pre_release:
    name: '🔨 Create Pre-release'
    runs-on: 'ubuntu-latest'
    permissions: write-all
    needs: [test]
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          lfs: true
          fetch-depth: 0

      - name: '🔧 setup node'
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16
          cache-dependency-path: 'yarn.lock'

      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn build'
      - run: 'yarn jest --env=node --colors --forceExit'

      - uses: './packages/automatic-releases/'
        id: 'automatic_releases'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: 'Development Build'
          files: |
            packages/automatic-releases/dist/index.js

      - name: 'Automatically mirror release artifacts'
        env:
          GITHUB_SUPER_TOKEN: ${{ secrets.GITHUB_SUPER_TOKEN }}
        run: |
          ./scripts/mirror-actions.sh "$AUTOMATIC_RELEASES_TAG"
