name: 'tests'

on:
  workflow_call:

jobs:
  gh_tests:
    name: 'Run tests'
    runs-on: 'ubuntu-latest'
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          lfs: true
          fetch-depth: 0

      - name: '🔧 setup node'
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16
          cache-dependency-path: 'yarn.lock'

      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn lint'
      - run: 'yarn build'
      - run: 'yarn jest --env=node --colors --forceExit'

      - name: 'Cancelling parallel jobs'
        if: failure()
        uses: andymckay/cancel-action@0.3
